### ISSUE TITLE
Setup query parser for pageviews

### ISSUE THREAD

**Issue by psiemens** [ubyssey/analytics-dashboard#7]

**Comment by JimFung** [comment]
Total page views per hours
https://ubyssey-analytics.appspot.com/query?id=ahNzfnVieXNzZXktYW5hbHl0aWNzchULEghBcGlRdWVyeRiAgICAr8iACgw&format=json

Total page views per day
Note: As per the google analytics api: 
> Day of the week, a one-digit number from 0 (Sunday) to 6 (Saturday)

https://ubyssey-analytics.appspot.com/query?id=ahNzfnVieXNzZXktYW5hbHl0aWNzchULEghBcGlRdWVyeRiAgICAgOSRCgw&format=json

**Comment by shanmango** [comment]
Total page views per hour:
[
"11", // hour
"16", // minute
"21" // pageviews
],

**Comment by shanmango** [comment]
Total page views per day
rows: [
[
"12", // hour
"2", // day of week
"27", // day of month
"1266" // pageviews
],
