### ISSUE TITLE
Setup query parser for top articles

### ISSUE THREAD

**Issue by psiemens** [ubyssey/analytics-dashboard#8]

**Comment by JimFung** [comment]
Endpoint for the query. Will update with more variations of the query as I set them up. You should be able to do /hour, /day, /week with these 2 queries now. 👍 

Page views (descending) for the past day in 1 hour chunks.
https://ubyssey-analytics.appspot.com/query?id=ahNzfnVieXNzZXktYW5hbHl0aWNzchULEghBcGlRdWVyeRiAgICA7a2SCgw&format=json

Top articles broken down by day for the past 7 days. 
Note: As per the google analytics api: 

> Day of the week, a one-digit number from 0 (Sunday) to 6 (Saturday)

https://ubyssey-analytics.appspot.com/query?id=ahNzfnVieXNzZXktYW5hbHl0aWNzchULEghBcGlRdWVyeRiAgICA7bGDCQw&format=json

**Comment by JimFung** [comment]
Example
```
[
      "/news/well-this-has-been-fun/", //URL
      "Alan Ehrenholz wins race for AMS President", //Title of article
      "19", //Hour
      "5", //Day of week
      "14995" //Pageviews
    ]
```
